#!/usr/bin/env bash
# flags.sh — workshop flag table, sourced by verify-fix/lib.sh and verify-exploit/lib.sh.
# Regenerated by scripts/rotate-flags.py from ctfd/challenges.json.
# DO NOT EDIT BY HAND — run `make -f Makefile.facilitator rotate-flags` instead.
#
# Two functions:
#   fix_flag_for <short_id>     — every "— Исправление" challenge
#   exploit_flag_for <short_id> — exploits where the running app cannot leak the
#                                 flag itself: DoS-style (3.1, 3.2),
#                                 identification-only (2.3, the CVE is a DoS
#                                 in language.Parse with nothing to exfil), and
#                                 oracle-style (3.3, recovered key isn't itself
#                                 the flag — server probe confirms the recovery)
#
# Case statements (not associative arrays) so this works on the bash 3.2 that
# macOS still ships by default. Each function returns 0 on hit, 1 on unknown id.

fix_flag_for() {
    case "$1" in
        "1.1") echo "GOSDL{9fd46ea20b0ad491}" ;;
        "1.3") echo "GOSDL{afd74383213e4b89}" ;;
        "1.4") echo "GOSDL{21b293e90b692b21}" ;;
        "2.1") echo "GOSDL{7b83dcd3de69ec70}" ;;
        "2.2") echo "GOSDL{25debc87f13ee34d}" ;;
        "2.3") echo "GOSDL{df1593570a421e05}" ;;
        "3.1") echo "GOSDL{62f10b3f248fee79}" ;;
        "3.2") echo "GOSDL{8cdc5fcdabc61d4a}" ;;
        "3.3") echo "GOSDL{87f616d8678bd646}" ;;
        "4.1") echo "GOSDL{36413d185fa15610}" ;;
        *) return 1 ;;
    esac
}

exploit_flag_for() {
    case "$1" in
        "2.3") echo "GOSDL{5a57f43821ca63a6}" ;;
        "3.1") echo "GOSDL{0d5db13b19e716bf}" ;;
        "3.2") echo "GOSDL{2985f816e2ef2245}" ;;
        "3.3") echo "GOSDL{f1442e0a0e88314f}" ;;
        *) return 1 ;;
    esac
}
